import { Car } from './types';

export const CARS: Car[] = [
  {
    id: 1,
    name: 'Tesla Model S',
    type: 'Electric',
    pricePerDay: 150,
    imageUrl: 'https://picsum.photos/seed/tesla/600/400',
    features: { seats: 5, transmission: 'Automatic', fuel: 'Electric' },
    status: 'Available',
    location: 'Main Lot, Aisle 3',
  },
  {
    id: 2,
    name: 'Porsche 911',
    type: 'Sports',
    pricePerDay: 350,
    imageUrl: 'https://picsum.photos/seed/porsche/600/400',
    features: { seats: 2, transmission: 'Automatic', fuel: 'Gasoline' },
    status: 'Available',
    location: 'Valet Section',
  },
  {
    id: 3,
    name: 'Range Rover',
    type: 'SUV',
    pricePerDay: 200,
    imageUrl: 'https://picsum.photos/seed/rangerover/600/400',
    features: { seats: 5, transmission: 'Automatic', fuel: 'Diesel' },
    status: 'Available',
    location: 'Main Lot, Aisle 2',
  },
  {
    id: 4,
    name: 'Mercedes-Benz S-Class',
    type: 'Luxury',
    pricePerDay: 280,
    imageUrl: 'https://picsum.photos/seed/mercedes/600/400',
    features: { seats: 5, transmission: 'Automatic', fuel: 'Gasoline' },
    status: 'Available',
    location: 'Executive Parking',
  },
  {
    id: 5,
    name: 'BMW M3',
    type: 'Sports',
    pricePerDay: 220,
    imageUrl: 'https://picsum.photos/seed/bmw/600/400',
    features: { seats: 4, transmission: 'Automatic', fuel: 'Gasoline' },
    status: 'Maintenance Required',
    location: 'Service Center',
  },
  {
    id: 6,
    name: 'Audi Q7',
    type: 'SUV',
    pricePerDay: 180,
    imageUrl: 'https://picsum.photos/seed/audi/600/400',
    features: { seats: 7, transmission: 'Automatic', fuel: 'Diesel' },
    status: 'Available',
    location: 'Family Section, Row B',
  },
   {
    id: 7,
    name: 'Honda Civic',
    type: 'Sedan',
    pricePerDay: 70,
    imageUrl: 'https://picsum.photos/seed/honda/600/400',
    features: { seats: 5, transmission: 'Automatic', fuel: 'Gasoline' },
    status: 'Available',
    location: 'Economy Lot',
  },
  {
    id: 8,
    name: 'Ford Mustang',
    type: 'Sports',
    pricePerDay: 190,
    imageUrl: 'https://picsum.photos/seed/mustang/600/400',
    features: { seats: 4, transmission: 'Manual', fuel: 'Gasoline' },
    status: 'Available',
    location: 'Main Lot, Aisle 5',
  },
];
